POST http://localhost:8080/api/v1/users/signin
Content-Type: application/json
X-CSRF-Token: {{csrf}}
Cookie: _csrf={{csrf}}
Cookie: my-session={{my-session}}

{
  "username": "johnny",
  "password": "j1234"
}

> {%
  response.headers.valuesOf("Set-Cookie").forEach(function(cookie) {
     if (cookie.startsWith("my-session")) {
         var sessionCookie = cookie.split("=")[1].split(";")[0]
         client.log(sessionCookie)
         client.global.set("my-session", sessionCookie)
     }
  });
 %}